### PR TITLE
feat: Update public_api.ts

### PR DESCRIPTION
**Pull request by duykhang53**
# I'm submitting a...

- [ ] Bug Fix
- [x] Feature
- [ ] Other (Refactoring, Added tests, Documentation, ...)

### Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
  - A document related commit is prefixed "docs:"
- [ ] Docs have been added / updated (for bug fixes / features)

### Description

This one fix configuration when import NgxEditorModule to submodules, allow developers to add NgxEditorService to component/module providers.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sibiraj-s** [comment]
the commit message does not follow conventional commit pattern.

**Comment by sibiraj-s** [comment]
Can you please elaborate the use case, the service is already provided to the module. why export it again?

**Comment by duykhang53** [comment]
The `NgxEditorService` is provided in **root** so it's only work in `AppModule`, it's not optimized the bundle size. What I want is it can be imported from the submodule. 
The configuration is not working in submodule if `NgxEditorService` is not in its `providers`.

**Comment by duykhang53** [comment]
Or you can add `NgxEditorService` to `forChild()` of `NgxEditorModule` providers to fix that without exporting.

```ts
import { InjectionToken, ModuleWithProviders, NgModule } from '@angular/core';

import { NgxEditorComponent } from './ngx-editor.component';
import { NgxEditorService, NgxEditorServiceConfig, provideMyServiceOptions } from './ngx-editor.service';
import { NgxEditorConfig } from './types';

const NGX_EDITOR_CONFIG_TOKEN = new InjectionToken<NgxEditorConfig>('NgxEditorConfig');

@NgModule({
  declarations: [NgxEditorComponent],
  exports: [NgxEditorComponent],
})

export class NgxEditorModule {
  static forRoot(config: NgxEditorConfig): ModuleWithProviders<NgxEditorModule> {

    return {
      ngModule: NgxEditorModule,
      providers: [
        {
          provide: NGX_EDITOR_CONFIG_TOKEN,
          useValue: config
        },
        {
          provide: NgxEditorServiceConfig,
          useFactory: provideMyServiceOptions,
          deps: [NGX_EDITOR_CONFIG_TOKEN]
        }
      ]
    };
  }

  static forChild(config: NgxEditorConfig): ModuleWithProviders<NgxEditorModule> {
    return {
      ngModule: NgxEditorModule,
      providers: [
        {
          provide: NGX_EDITOR_CONFIG_TOKEN,
          useValue: config
        },
        {
          provide: NgxEditorServiceConfig,
          useFactory: provideMyServiceOptions,
          deps: [NGX_EDITOR_CONFIG_TOKEN]
        },
        NgxEditorService,
      ]
    };
  }
}
```

**Pull request closed without merging**
