### PR TITLE
Fontawesome updated to 5.0.10

### PR DESCRIPTION
**Pull request by VladimirHumeniuk**
# I'm submitting a...

- [ ] Bug Fix
- [x] Feature
- [ ] Other (Refactoring, Added tests, Documentation, ...)

### Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
  - A document related commit is prefixed "docs:"
- [ ] Docs have been added / updated (for bug fixes / features)

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Does this PR affects any existing issues?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Sibiraj-S** [comment]
hi @VladimirHumeniuk , There are reasons why I didn't update to Font Awesome 5, Main reason is that features and customization are limited in free version, I can't force users to use solid icons they look really bad at some cases.

Instead what I planned is to have custom toolbar, design the toolbar as users wish, Font awesome 5 or material, or whatever they like.

**Comment by VladimirHumeniuk** [comment]
@Sibiraj-S  Okay, seems rightfully. By the way, also would be great, if we could add additional buttons into toolbar.

**Comment by Sibiraj-S** [comment]
> if we could add additional buttons into toolbar.

yes, when toolbar customization is possible. Its all yours

**Comment by Sibiraj-S** [comment]
@VladimirHumeniuk . Also follow conventional commits while making any changes. Thanks for the PR. 🍻

**Pull request closed without merging**
