### PR TITLE
Added support for no menu rendering and removed the extra space rende…

### PR DESCRIPTION
**Pull request by ARKEOLOGIST**
…red if null is deliberately passed to the toolbar prop

# I'm submitting a...

- [ ] Bug Fix
- [X] Feature
- [ ] Other (Refactoring, Added tests, Documentation, ...)

### Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
  - A document related commit is prefixed "docs:"
- [ ] Docs have been added / updated (for bug fixes / features)

### Description

Should the toolbar prop be passed a null or undefined value deliberately, the menu will not be rendered as a DOM node, saving space on the editor.

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### Does this PR affects any existing issues?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by ARKEOLOGIST** [comment]
@sibiraj-s please have a look at this PR.

**Comment by sibiraj-s** [comment]
Sure. I will look into. Thanks for the contribution. Code is now readable.

If you don't pass `menu` in the plugins. It shouldn't render the toolbar. is it not working?

**Comment by ARKEOLOGIST** [comment]
Actually, it also causes a problem in the editor for some reason. You can't type in anything. 

The only way seems to be not to append the DOM node for the menu at all.

**Comment by sibiraj-s** [comment]
Hi. Sorry for the delay in response. got bit occupied.

> Actually, it also causes a problem in the editor for some reason. You can't type in anything.

can you post your config or a stackblitz reproducing this?

**Comment by ARKEOLOGIST** [comment]
I'm just passing null to the menu. I'll post a stackblitz soon.

**Comment by ARKEOLOGIST** [comment]
@sibiraj-s Please have a look at these images. The first two images show the config (not passing menu), and the second image shows the output. The editor doesn't respond if you pass null to plugins and renders an extra white space (third image) above the text area (basically an empty DOM node being appended for no reason). This PR will prevent that DOM node from being added, so anyone who wishes to just have the text area can just pass in null to plugins (or to the toolbar itself).

https://imgur.com/BZs8gRY
https://imgur.com/yL4d3WK
https://imgur.com/Go6qCei

**Comment by sibiraj-s** [comment]
@ARKEOLOGIST that is no whitespace. that is the margin of the heading and padding in editor, giving you the impression. Plus. passing null doesn't makes the editor unresponsive. by default the editor comes with no features you will have to enable them manually as required.

For example to enable shortcuts see https://sibiraj.dev/ngx-editor/additional-documentation/shortcuts.html

See wiki for more details https://sibiraj.dev/ngx-editor/additional-documentation/configuration.html.
or see the stackblitz https://stackblitz.com/edit/ngx-editor for reference,

**Comment by sibiraj-s** [comment]
This PR is not the solution for the problem you face. Closing this now. Feel free to post question on the same thread. Happy to help.

**Note** v5 is still in alpha. there are some features yet to be added

**Pull request closed without merging**
