### PR TITLE
Feature: Adding Link Validation Pattern of Link Component to Editor Config

### LINKED ISSUE #396: [Bug]: Protocols are not automatically added to the generated urls.
### What happened?

If you add a link, the editor does not automatically add the protocol, either http, https... so if the user simply enters google.es, this will redirect to https://mywebsite/google.es which is totally incorrect and frustrating for the user who clicks on the link. It would be better to add this header automatically, like ngx-quill or other editors do, or at least offer this one.

### Version

v12.2.2

### Angular Version

v13.3.2

### What browsers are you seeing the problem on?

Firefox, Chrome

### Link to reproduce

https://stackblitz.com/edit/angular-ivy-1fpe4o

### Relevant log output

_No response_

### Willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by schmoizz**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [x] documentation
- [ ] others

### Breaking Changes?

- [ ] yes
- [x] no

### Checklist

- [x] commit messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
  - A document related commit is prefixed "docs:"
- [x] docs have been added / updated (for bug fixes / features)

### Describe Your Changes

Validation Pattern in the Link Component can now be set with a configuration in Editor.
Use linkValidationPattern option to achive it. If option is not set the default is used.

### Does this PR affects any existing issues?

- [x] yes
- [ ] no

closes #396

### CODE REVIEW

**Review by sibiraj-s — APPROVED** [review]

**Comment by sibiraj-s** [comment]
Thanks @schmoizz.

**Comment by schmoizz** [comment]
No Problem @sibiraj-s.
Can you maybe pack this new functionality into a release? I have a project on hand where i need it quite urgent.
Thanks in advance.

**Comment by sibiraj-s** [comment]
Sure @schmoizz . I merged a breaking change yesterday that requires angular 14.1.0, was testing some aspects of it hence the delay. I will do the release today.

**Comment by sibiraj-s** [comment]
Published in [v15.0.0](https://github.com/sibiraj-s/ngx-editor/releases/tag/v15.0.0) 🎉

**Pull request merged**
