### PR TITLE
Added to Event Emitter to receive 'blur' and 'focus' events from parent component which holds the Editor.

### PR DESCRIPTION
**Pull request by senthil090**
Some events have been handled internally, there were no public api to handle this event from parent component. i have just emit the blur and focus event which handled for disable the buttons on toolbar. now we can receive this from parent.

### CODE REVIEW

**Comment by Sibiraj-S** [comment]
when will this come in handy. I thought that was unnecessary. can you provide an example?

**Comment by senthil090** [comment]
Let us assume that we use this editor inside a form and we would like to
have this editor as a form element. Form elements should have this options
to make it more customizable.
And also we have to make the validation for the editor that supports
reactive form as well as template driven.

**Comment by Sibiraj-S** [comment]
Can we provide more unique name for the events. Those names are more universal.

**Comment by Sibiraj-S** [comment]
such as onFocus or onEditorFocus, etc.

**Comment by senthil090** [comment]
Lint not allowed to create the class property name prefixed with 'On' and not allowed to use reference name in Output decorator. Also we already have onBlur and onFocus as methods.

**Comment by Sibiraj-S** [comment]
oh. do we 😸

**Comment by Sibiraj-S** [comment]
for now I will merge this. Will see the rest later.

**Comment by senthil090** [comment]
Thank you :+1:

**Pull request merged**
